[32mINFO    [0m first.conftest:conftest.py:24 started executing test_physical_reward_redemption
[32mINFO    [0m first.test_setup:test_setup.py:48 quit appium driver
[32mINFO    [0m first.test_setup:test_setup.py:51 stop appium service
[32mINFO    [0m first.test_setup:test_setup.py:53 -------- rewardz app: closing module first.rewardz.test_rewardz---------